g.addV('concept').property('id','RDV').property('name','Root Device Volume').property('key-phrases', 'Contains the image used to boot the instance')
g.V('RDV').property(list, 'key-phrases', 'Gets create for each new instance automatically')
g.V('RDV').property(list, 'key-phrases', 'In begining of AWS it was backed by Amazon EC2 Instance Store')
g.V('RDV').property(list, 'key-phrases', 'Instance store was created by a template stored in S3')
g.V('RDV').property(list, 'key-phrases', 'Now Elastic Block Storage also known as EBS are used')
g.V('RDV').property(list, 'key-phrases', 'Image used to boot instance is copied to root volume')
g.addV('concept').property('id','ISV').property('name', 'Instance Store Volume').property('key-phrases', 'Known as Instance Store')
g.V('ISV').property(list, 'key-phrases', 'Data persists as long as instance runs')
g.V('ISV').property(list, 'key-phrases', 'Can have 1 or more instance store volumes')
g.V('ISV').property(list, 'key-phrases', 'On instance termination / failure the instance store volumes are lost')
g.V('ISV').property(list, 'key-phrases', 'Data once lost cannot be restored.')
g.V('ISV').property(list, 'best-practices', 'Back up data to persistent storage on a regular basis')
g.V('Instance').addE('NEEDS').to(g.V('RDV'))
g.V('Instance').addE('HAS_FEATURE').to(g.V('ISV'))
g.V('RDV').addE('SPECIALIZES').to(g.V('ISV'))
g.V('Instance').addE('NEEDS').to(g.V('InstanceType')).property('notes','To define the hardware capabilities of the machine')
g.V('Instance').outE().hasLabel('USES').as('a').inV().where(is('InstanceType')).select('a').drop()
g.V('InstanceType').addE('SUPPORTS').to(g.V('ISV')).property('notes', 'ONLY for  C3, D2, G2, I2, M3, R3')
g.V('AMI').addE('HAS_FEATURE').to(g.V('ISV'))
g.V('ISV').addE('CONTRIBUTES_RESILIENCY').to(g.V('AvailabilityZone')).property('notes','For instances using instance store, it is recommended to distribute the instance store across multiple Availability Zones')
g.addV('concept').property('id', 'EBSV').property('name', 'EBS Volume').property('key-phrases','Concept which stores block level data for instance attached or detacched to instance.')
g.V('EBSV').property(list, 'key-phrases', 'Aides in changing associated instance size, kernel etc.')
g.V('EBSV').property(list, 'key-phrases', 'Can be attached to another instance where it is not RDV')
g.V('EBSV').property(list, 'key-phrases', 'Can be restored if there are technical failures')
g.V('EBSV').property(list, 'key-phrases', 'Snapshots can be taken of EBS')
g.V('EBS').addE('HAS_CONCEPT').to(g.V('EBSV'))
g.V('RDV').addE('SPECIALIZES').to(g.V('EBSV'))
g.V('Instance').addE('HAS_FEATURE').to(g.V('EBSV'))
g.V('AMI').addE('HAS_FEATURE').to(g.V('EBSV'))
g.V('CLI').addE('OPERATES_ON').to(g.V('AMI')).property('notes','Command is describe-images')
g.V('PWSH').addE('OPERATES_ON').to(g.V('AMI')).property('notes','Command is Get-EC2Image')